# Generated by Django 4.1.7 on 2023-02-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
