# Generated by Django 4.1.7 on 2023-02-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_hub', '0002_alter_book_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='url',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
