# Generated by Django 4.1.7 on 2023-02-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_hub', '0005_alter_category_name_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(unique=True, upload_to='static/books/<django.db.models.fields.SlugField>', verbose_name='Book file'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Book name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='poster',
            field=models.ImageField(unique=True, upload_to='static/books/<django.db.models.fields.SlugField>', verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tagline',
            field=models.CharField(default='', max_length=150, verbose_name='Tagline for book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.SlugField(blank=True, help_text='leave it for autogenerate', max_length=150, unique=True),
        ),
    ]
