# Generated by Django 4.1.7 on 2023-03-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_hub', '0007_alter_book_file_alter_book_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tagline',
            field=models.CharField(default='', max_length=50, verbose_name='Tagline for book'),
        ),
    ]
